### ISSUE TITLE
No Executable or Instructions to Make Build

### ISSUE THREAD

**Issue by Starwolf-001** [Sinflower/WolfDec#1]
Any chance to update instructions in ReadMe for a uild or include an executable file?

**Comment by Sinflower** [comment]
An executable can be found here:
https://github.com/Sinflower/WolfDec/releases
As for build instructions, it appears I forgot to include the project file, will upload it in a moment.

**Comment by Sinflower** [comment]
I have just now added the Visual Studio project required to build the executable.

**Comment by Starwolf-001** [comment]
I looked in the wrong section. Thank you. The project file would have been helpful. Thank you.
