### ISSUE TITLE
Trying to recreate in python, can't understand Huffman_Decode

### ISSUE THREAD

**Issue by Bexa2** [Sinflower/WolfDec#3]
Hi, I'm trying to recreate this in python.

I'm stuck on `DXArchive::DecodeArchive()`
I've been adding printf's to the code so I can follow along and compare what I get with what your program gives.

So, on this part:
```c++
void *HuffHeadBuffer ;
u64 HuffHeadSize ;
void *LzHeadBuffer ;
u64 LzHeadSize ;
// ハフマン圧縮されたヘッダのサイズを取得する
_fseeki64( ArcP, 0, SEEK_END ) ;
FileSize = _ftelli64( ArcP ) ;
_fseeki64( ArcP, Head.FileNameTableStartAddress, SEEK_SET ) ;
HuffHeadSize = ( u32 )( FileSize - _ftelli64( ArcP ) ) ;

printf("Huffman compressed header size = %llu\n", HuffHeadSize);

// ハフマン圧縮されたヘッダを読み込むメモリを確保する
HuffHeadBuffer = malloc( ( size_t )HuffHeadSize ) ;
if( HuffHeadBuffer == NULL ) goto ERR ;

// ハフマン圧縮されたヘッダをコピーと暗号化解除
KeyConvFileRead( HuffHeadBuffer, HuffHeadSize, ArcP, NoKey ? NULL : Key, 0 ) ;

printf(NoKey ? "There's no Key\n" : "There's a Key\n");


// ハフマン圧縮されたヘッダの解凍後の容量を取得する
LzHeadSize = Huffman_Decode( HuffHeadBuffer, NULL ) ;

printf("Huffman compressed header size decompressed = %llu\n", LzHeadSize);

// ハフマン圧縮されたヘッダの解凍後のデータを格納するメモリ用域の確保
LzHeadBuffer = malloc( ( size_t )LzHeadSize ) ;
if( LzHeadBuffer == NULL )
{
	free( HuffHeadBuffer ) ;
	goto ERR ;
}


// ハフマン圧縮されたヘッダを解凍する
Huffman_Decode( HuffHeadBuffer, LzHeadBuffer ) ;
```

I get the same output, in both python and C++:

```
Huffman compressed header size = 3789
There's a Key
headSize=460
Huffman compressed header size decompressed = 4364
headSize=460
originalSize=4364
destSize=4364
```

However I'm running into a problem in the decompression step, instead of allocating memory like in C++, in python I'm creating an array of bytes with a set size.

On this part on Huffman.cpp
```c++
// 圧縮データ本体の先頭アドレスをセット
// (圧縮データ本体は元のサイズ、圧縮後のサイズ、各数値の出現数等を
// 格納するデータ領域の後にある)

/*for (size_t i = 0; i < 3789; i++)
{
    unsigned char c = ((char*)PressPoint)[i];
    printf("%i - %02x\n", i, c);
}
std::cout << std::endl;*/

PressData = PressPoint + HeadSize ;

//for (size_t i = 0; i < 3789-HeadSize; i++)
//{
//    unsigned char c = ((char*)PressData)[i];
//    printf("%i - %02x\n", i, c);
//}
//std::cout << std::endl;

// 解凍したデータの格納アドレスを初期化
DestSizeCounter = 0 ;

// 圧縮データの参照アドレスを初期化
PressSizeCounter = 0 ;

// 圧縮ビットデータのカウンタを初期化
PressBitCounter = 0 ;

// 圧縮データの１バイト目をセット
PressBitData = PressData[PressSizeCounter] ;

// 圧縮前のデータサイズになるまで解凍処理を繰り返す

for( DestSizeCounter = 0 ; DestSizeCounter < DestSize ; DestSizeCounter ++ )
{
    printf("destSizeCounter=%llu\n", DestSizeCounter);
    printf("pressSizeCounter=%llu\n", PressSizeCounter);
    // ビット列から数値データを検索する
    {
        // 最後の17byte分のデータは天辺から探す( 最後の次のバイトを読み出そうとしてメモリの不正なアクセスになる可能性があるため )
        if( DestSizeCounter >= DestSize - 17 )
        {
            // 結合データの天辺は一番最後の結合データが格納される５１０番目(０番から数える)
            // 天辺から順に下に降りていく
            NodeIndex = 510 ;
        }
        else
        {
            // それ以外の場合はテーブルを使用する

            // もし PressBitData に格納されている全ての
            // ビットデータを使い切ってしまった場合は次の
            // ビットデータをセットする
            if( PressBitCounter == 8 )
            {
                PressSizeCounter ++ ;
                PressBitData = PressData[PressSizeCounter] ;
                PressBitCounter = 0 ;
            }
            
            // 圧縮データを9bit分用意する
            //printf("%llu/%llu\n", PressSizeCounter + 1, &PressData);
            int tmp1 = PressData[PressSizeCounter + 1];
            PressBitData = ( PressBitData | ( tmp1 << ( 8 - PressBitCounter ) ) ) & 0x1ff ;

            // テーブルから最初の結合データを探す
            NodeIndex = NodeIndexTable[ PressBitData ] ;

            // 使った分圧縮データのアドレスを進める
            PressBitCounter += Node[ NodeIndex ].BitNum ;
            if( PressBitCounter >= 16 )
            {
                PressSizeCounter += 2 ;
                PressBitCounter -= 16 ;
                PressBitData = PressData[PressSizeCounter] >> PressBitCounter ;
            }
            else
            if( PressBitCounter >= 8 )
            {
                PressSizeCounter ++ ;
                PressBitCounter -= 8 ;
                PressBitData = PressData[PressSizeCounter] >> PressBitCounter ;
            }
            else
            {
                PressBitData >>= Node[ NodeIndex ].BitNum ;
            }
        }
        
        // 数値データに辿り着くまで結合データを下りていく
        while( NodeIndex > 255 )
        {
            // もし PressBitData に格納されている全ての
            // ビットデータを使い切ってしまった場合は次の
            // ビットデータをセットする
            if( PressBitCounter == 8 )
            {
                PressSizeCounter ++ ;
                PressBitData = PressData[PressSizeCounter] ;
                PressBitCounter = 0 ;
            }
            
            // １ビット取得する
            Index = PressBitData & 1 ;
            
            // 使用した１ビット分だけ右にシフトする
            PressBitData >>= 1 ;
            
            // 使用したビット数を一個増やす
            PressBitCounter ++ ;
            
            // 次の要素(結合データか数値データかはまだ分からない)に移る
            NodeIndex = Node[NodeIndex].ChildNode[Index] ;
        }
    }

    // 辿り着いた数値データを出力
    DestPoint[DestSizeCounter] = (unsigned char)NodeIndex ;
    printf("DestPoint[DestSizeCounter] = %i\n", NodeIndex);
}
```

`PressPoint` and `DestPoint` are used (I don't know much C but I believe they're pointers to memory), since I'm using arrays with fixed size , when you do `PressData = PressPoint + HeadSize ;` (I believe if `PressPoint` was pointing at x in memory, `PressData` is pointing now at x+HeadSize ??)

To kind of replicate that my `PressData` array is `PressPoint[HeadSize:]` so just like `PressPoint` but starting at the `HeadSize` position and shorter. Now the length of PressData is the compressed header size (3789) minus HeadSize (460) so (3329).

Everything works until the `for( DestSizeCounter = 0 ; DestSizeCounter < DestSize ; DestSizeCounter ++ )` loop.

In this diff of the printf's outputs we can see that up until `DestSizeCounter=3328` it's all the same, but when it reaches the end of my array, while in C++ it can keep reading memory, in python I can not.

https://i.imgur.com/WalB9xE.png

When `DestPoint[DestSizeCounter] = 117` that's just zeros, but then there's some random bytes and I'm not sure if they're important or they will get discarded later.
So that's my main question, is it okay to fill `PressData` with zeros so it doesn't fail on my fixed size array or are the bytes read from memory important. Not sure if I'm explaining myself correctly...

THEN when Huffman_Decode() is done and it's time for Decode() `LZ圧縮されたヘッダを解凍する` the program crashes because of this error:

https://i.imgur.com/RqFgcyn.png

"Access violation reading location" I think.

Here's the Data.wolf that's giving me trouble.
[Data.zip](https://github.com/Sinflower/WolfDec/files/8034384/Data.zip)

Also, do you have any .wolf or .dxa files that you know 100% work with each version and key to test my python version?

- `DXArchive_VER5` with the key `gKEY_2_10`
- `DXArchive_VER5` with the key `gKEY_2_10_2`
- `DXArchive_VER6` with the key `gKEY_2_20`
- `DXArchive` with key `WLFRPrO!p(;s5((8P@((UFWlu$#5(=` (Is this v8?)

**Comment by Sinflower** [comment]
Is the attached file the one you used for the Python testing, i.e., the one that produced the compressed/decompressed and headSize values printed above?
If so, there appears to be a problem in your implementation, as I get:
Huffman compressed header size = 3789
headSize=350
Huffman compressed header size decompressed = 4292
headSize=350

Furthermore, if you look at the beginning of Huffman_Decode(), primarily this part:

```
OriginalSize = BitStream_Read(&BitStream, (u8)(BitStream_Read(&BitStream, 6) + 1));
PressSize = BitStream_Read(&BitStream, (u8)(BitStream_Read(&BitStream, 6) + 1));

// 出現頻度のテーブルを復元する
BitNum = (u8)(BitStream_Read(&BitStream, 3) + 1) * 2;
Minus = (u8)BitStream_Read(&BitStream, 1);
SaveData = (u16)BitStream_Read(&BitStream, BitNum);
Weight[0] = SaveData;
for (i = 1; i < 256; i++)
{
	BitNum = (u8)(BitStream_Read(&BitStream, 3) + 1) * 2;
	Minus = (u8)BitStream_Read(&BitStream, 1);
	SaveData = (u16)BitStream_Read(&BitStream, BitNum);
	Weight[i] = Minus == 1 ? Weight[i - 1] - SaveData : Weight[i - 1] + SaveData;
}

HeadSize = BitStream_GetBytes(&BitStream);
```

`PressSize` should equal `OriginalSize - HeadSize` and will also be the number of elements read from `PressData`.

> PressPoint and DestPoint are used (I don't know much C but I believe they're pointers to memory), since I'm using arrays with fixed size , when you do PressData = PressPoint + HeadSize ; (I believe if PressPoint was pointing at x in memory, PressData is pointing now at x+HeadSize ??)

Yes, that's correct, in this case `PressData` points to the data `HeadSize` byte after `PressPoint`.

> THEN when Huffman_Decode() is done and it's time for Decode() LZ圧縮されたヘッダを解凍する the program crashes because of this error:

I am unable to reproduce this error, for me the file decrypts without any problems.

> Also, do you have any .wolf or .dxa files that you know 100% work with each version and key to test my python version?

Not at the moment, but you can just take a look at the list published here:
https://wiki.xentax.com/index.php/DX_Archive#Keys
to find the corresponding WolfRPG version and then download that version here:
https://www.silversecond.com/WolfRPGEditor/Download.html
afterwards, just create a test archive with each version and you should have your test data.

**Comment by Bexa2** [comment]
Ugh, I'm stupid.
I had broken down 
```c++
OriginalSize = BitStream_Read(&BitStream, (u8)(BitStream_Read(&BitStream, 6) + 1));
PressSize = BitStream_Read(&BitStream, (u8)(BitStream_Read(&BitStream, 6) + 1));
```

into

```c++
u8 tmp1 = (u8)(BitStream_Read(&BitStream, 6) + 1);
u8 tmp2 = (u8)(BitStream_Read(&BitStream, 6) + 1);

printf("tmp1=%u\n", tmp1);
printf("tmp2=%u\n", tmp2);

OriginalSize = BitStream_Read( &BitStream, tmp1) ;
PressSize    = BitStream_Read( &BitStream, tmp2) ;

printf("originalSize=%llu\n", OriginalSize);
printf("pressSize=%llu\n", PressSize);
```
To check that I was getting the same values in all steps in python and C++, and I was but I also thought that since "it's just reading" no changes to BitStream were being made, ignoring the `BitStream->Bits` and `BitStream->Bytes`

So I was probably reading something like `ABAB` instead of `AABB`.

I guess I wouldn't have had this problem if I had done

```c++
u8 tmp1 = (u8)(BitStream_Read(&BitStream, 6) + 1);
OriginalSize = BitStream_Read( &BitStream, tmp1) ;

u8 tmp2 = (u8)(BitStream_Read(&BitStream, 6) + 1);
PressSize    = BitStream_Read( &BitStream, tmp2) ;

printf("tmp1=%u\n", tmp1);
printf("tmp2=%u\n", tmp2);

printf("originalSize=%llu\n", OriginalSize);
printf("pressSize=%llu\n", PressSize);
```

No wonder I was getting like 8 figure numbers for PressSize and running into problems trying to read...

Now let's see if I can understand DXArchive::Decode()

Thanks!

Edit:

Got `DXArchive::Decode()` working!!
