### ISSUE TITLE
Unable to extract files from Steam version of the One Way Heroics game

### ISSUE THREAD

**Issue by Pysis868** [Sinflower/WolfDec#4]
Does this repository help with that file format?  Seems this project deals with some DX data format:
`Unpacking: BGM... fish: Job 1, '…' terminated by signal SIGSEGV (Address boundary error)`
Produces empty folders along with that error message.  Tried multiple `wolf` files.

`...\One Way Heroics\Data\BGM.wolf`
`One Way Heroics\Data\BGM.wolf: data`
```
00000000: 4458 0800 742c 0000 4000 0000 0000 0000  DX..t,..@.......
00000010: 9cda e800 0000 0000 1c16 0000 0000 0000  ................
00000020: 542c 0000 0000 0000 a403 0000 0000 0000  T,..............
00000030: 0a00 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 1252 2717 7e22 9252 a66a 437f 4292 5258  .R'.~".R.jC.B.RX
00000050: 2117 1626 9152 386a 4365 4d92 5258 7d17  !..&.R8jCeM.RX}.
00000060: e825 84d9 baa5 db99 6901 a8d4 a996 77b6  .%......i.....w.
00000070: ccc0 d3a5 dbe9 269b 52a7 251f 9969 1fba  ......&.R.%..i..
00000080: d967 8741 266d 53a6 8f32 4625 9923 e8b5  .g.A&mS..2F%.#..
00000090: e917 219f 466e 47e9 0728 92ad 7727 e907  ..!.FnG..(..w'..
```

**Comment by Sinflower** [comment]
Please try the decoder from the attached archive, WolfDec_OWH_N for the files in the Data folder and WolfDec_OWH_P for the files in the DataPLUS folder.

One Way Heroics uses different decryption keys for Normal and Plus and the new version of DXArchive does not really like wrong keys, resulting in the quick and dirty way of creating two different decrypters.

[OneWayHeroic_Dec.zip](https://github.com/Sinflower/WolfDec/files/8160952/OneWayHeroic_Dec.zip)

**Comment by Pysis868** [comment]
Where did those files come from?

**Comment by Sinflower** [comment]
I recompiled the tool with different decryption keys, as currently for the latest DXArchive version the testing of different keys does not work.
