### ISSUE TITLE
Can't Decrypt version 8 of the DXArchive with WolfDec

### ISSUE THREAD

**Issue by Kayot** [Sinflower/WolfDec#5]
I'm able to unpack with DxLib_VC3_24 with a newer encryption key.

WLFRPrO!p(;s5((8P@((UFWlu$#5(=

Edit: Which matches the key in your source.

**Comment by Sinflower** [comment]
Strange, can you tell me which game you are trying to decrypt?

**Comment by Kayot** [comment]
You caught me doing the edit with the game name.

It's a NSFW game called Chevalier HIstorie Append

**Comment by Sinflower** [comment]
Are you sure you are using the latest release?
Because using the latest release I had no problems extracting all .wolf files for that game.

**Comment by Kayot** [comment]
That was it. Sorry to bother you. Have a good day.
