### ISSUE TITLE
Can't decode the files of one of the newest WolfRPG games.

### ISSUE THREAD

**Issue by Sabrox95** [Sinflower/WolfDec#7]
Hi. I can't decode the files of one of the newest WolfRPG games.
WolfDec v0.3.3 just creates an empty folder with the *.wolf archive name, but won't extract the files from it.

Here is a link to the game files for evaluation purposes:
[https://workupload.com/file/CJU3689yKs6](https://workupload.com/file/CJU3689yKs6)

Thanks in advance.

**Comment by Sinflower** [comment]
Hi,
looks like the dev used a different decrypt key for the game (did not know Wolf RPG offered that option).
I attached a version of WolfDec containing the key required to unpack this game.
If you encounter any errors or problems, please let me know.
[WolfDec.zip](https://github.com/Sinflower/WolfDec/files/12730920/WolfDec.zip)

**Comment by Sabrox95** [comment]
Thank you. Seems to be working now.
